name: Deploy And Test
on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy and Run Tests on Server
        run: |
          # Stop execution if any command fails
          set -e
          set -o pipefail

          # Define server credentials
          SERVER="${{ secrets.SERVER }}"
          USERNAME="${{ secrets.SERVER_USERNAME }}"
          PASSWORD="${{ secrets.SERVER_PASSWORD }}"
          REMOTE_DIR="${{ secrets.SERVER_DIR }}"

          # Use sshpass for password-based SSH login and run the commands remotely
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER << EOF
            # Navigate to the project directory
            cd $REMOTE_DIR || exit 1

            # Reset any local changes and pull the latest code
            echo "Resetting git and pulling the latest code..."
            git reset --hard HEAD || exit 1
            git checkout develop || exit 1
            git pull enpiidev develop || exit 1

            # Install dependencies
            echo "Installing Composer dependencies..."
            composer install || exit 1

            echo "Installing Yarn dependencies..."
            yarn install || exit 1

            echo "Building plugin..."
            yarn build-plugin || exit 1

            # Run PHPUnit tests
            echo "Running PHPUnit tests..."
            yarn phpunit || exit 1
          EOF
